server {
    listen 80;
    server_name multi.takitahmid.com *.multi.takitahmid.com;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 443 ssl;
    server_name multi.takitahmid.com *.multi.takitahmid.com;

    ssl_certificate     /etc/letsencrypt/live/multi.takitahmid.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/multi.takitahmid.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
